type Project {
    id: String!
    title: String!
    content: String!
    link: String
    repo: String
}

input ProjectInput {
    title: String!
    content: String!
    link: String
    repo: String
}

input ProjectUpdateInput {
    title: String
    content: String
    link: String
    repo: String
}

type Query {
    project(selector: String!): Project
    projects: [Project!]!
}

type Mutation {
    addProject(payload: ProjectInput!): Project!
    editProject(id: String!, payload: ProjectUpdateInput!): Project!
    deleteProject(id: String!): Boolean!
}
